global:

# The root route on which each incoming alert enters.
route:
  group_wait: 30s

  # When the first notification was sent, wait 'group_interval' to send a batch
  # of new alerts that started firing for that group.
  group_interval: 5m

  # If an alert has successfully been sent, wait 'repeat_interval' to
  # resend them.
  repeat_interval: 1m

  receiver: "scale-out"

  routes:
  - match:
      alertname: ContainerQuantityOver
    receiver: 'scale-out'
  - match:
      alertname: ContainerIdle
    receiver: 'scale-in'

receivers:
- name: 'scale-out'
  webhook_configs:
  - url: "http://172.16.6.59:8778/v1/webhooks/4bb56da2-2a40-45a1-bd55-f8b35206c211/trigger?V=1"
- name: 'scale-in'
  webhook_configs:
  - url: "http://172.16.6.59:8778/v1/webhooks/eb0fcdeb-095e-4165-9d18-ffcd2ede4dd0/trigger?V=1"
