#!/bin/bash

pip install python-glanceclient==0.17.3
pip install python-novaclient==2.23.0
pip install python-heatclient==0.6.0
pip install python-keystoneclient==1.3.0

sudo docker pull consul:latest
sudo docker pull gliderlabs/registrator:latest
sudo docker pull google/cadvisor:latest
sudo docker pull prom/node-exporter
sudo docker pull prom/prometheus:latest
sudo docker pull prom/alertmanager:latest
sudo docker pull yuanying/ubuntu-ruby:2.3.1
sudo docker pull sameersbn/redis:latest
sudo docker pull sameersbn/postgresql:9.5-1
sudo docker pull sameersbn/gitlab:8.11.4
