#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

pip install python-glanceclient==0.17.3
pip install python-novaclient==2.23.0
pip install python-heatclient==0.6.0
pip install python-keystoneclient==1.3.0
