#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

sudo docker pull consul:latest
docker save consul:latest > $TMP_HOOKS_PATH/consul.tar
sudo docker pull gliderlabs/registrator:latest
docker save gliderlabs/registrator:latest > $TMP_HOOKS_PATH/registrator.tar
sudo docker pull google/cadvisor:latest
docker save google/cadvisor:latest > $TMP_HOOKS_PATH/cadvisor.tar
sudo docker pull prom/node-exporter
docker save prom/node-exporter > $TMP_HOOKS_PATH/node-exporter.tar
sudo docker pull prom/prometheus:latest
docker save prom/prometheus:latest > $TMP_HOOKS_PATH/prometheus.tar
sudo docker pull prom/alertmanager:latest
docker save prom/alertmanager:latest > $TMP_HOOKS_PATH/alertmanager.tar
sudo docker pull yuanying/ubuntu-ruby:2.3.1
docker save yuanying/ubuntu-ruby:2.3.1 > $TMP_HOOKS_PATH/ubuntu-ruby.tar
sudo docker pull sameersbn/redis:latest
docker save sameersbn/redis:latest > $TMP_HOOKS_PATH/redis.tar
sudo docker pull sameersbn/postgresql:9.5-1
docker save sameersbn/postgresql:9.5-1 > $TMP_HOOKS_PATH/postgresql.tar
sudo docker pull sameersbn/gitlab:8.11.4
docker save sameersbn/gitlab:8.11.4 > $TMP_HOOKS_PATH/gitlab.tar
sudo docker pull yuanying/gitlab-runner:latest
docker save yuanying/gitlab-runner:latest > $TMP_HOOKS_PATH/gitlab-runner.tar
